apiVersion: v1
kind: Service
metadata:
  namespace: clamav
  name: clamav-rest-api
spec:
  type: NodePort
  selector:
    app: clamav-rest-api
  ports:
    - protocol: TCP
      port: 3000
      nodePort: 30080
